### ISSUE TITLE
Hi Ed Williams I'm MrAddon

### ISSUE THREAD

**Issue by rpelaez** [isometimesgit/videoassistant#10]
Off topic

**Comment by isometimesgit** [comment]
Hi,
Doing some simple Firefox add-ons should not be a problem.
Could you give me a rough idea of what you have in mind so I can estimate
how long it might take and we can go from there.

Best Regards,
Ed.

( Good to meet another MrAddon :)

**Comment by rpelaez** [comment]
Hi Ed, yes basically are 5 plugins (actually are 5 Google chrome plugins).
The plugins executes a Javascript file (limited to some webs/domains of Jira Cloud) and that's all!

Kanban Combined WIP for Jira Cloud:
https://chrome.google.com/webstore/detail/jira-cloud-kanban-combine/hpmnhocaonfpflchaabcekbhbhijmchj?hl=es-419Descubre

Jirasupport Admin Tools for Jira Cloud:
https://chrome.google.com/webstore/detail/jirasupport-admin-tools-f/lmomjjhiaclieneafebehojipblekdjm/support?hl=es-419

Issue Card Printer for Jira Cloud:
https://chrome.google.com/webstore/detail/issue-card-printer-for-ji/dkmmlbjfgplmmpgebddbdanhgfjmbkfg?hl=es-419.Tutorial%20Como%20Tunear%20Tu%20Google%20ChromePara

New Status Colors for Jira Cloud:
https://chrome.google.com/webstore/detail/new-status-colors-pro-for/ambfnpmanbfkcfoocddoicfaodljjahb?hl=es-419PARA

Description Templates for Jira Cloud:
https://chrome.google.com/webstore/detail/description-templates-for/ldfmmniipbadjdhnfphmaahdgbfppjim?hl=es-419.Tutorial%20Como%20Tunear%20Tu%20Google%20ChromePara

Can we talk using mail better? raulpelaez@mraddon.com
Many thanks and best regards!
